version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
